on: [pull_request, workflow_dispatch]
name: Validate JSON schema
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: batista/lint-filenames@v1
        name: Validating filenames
        with:
          path: './'
          pattern: '^[a-zA-Z0-9._-]*\/[a-zA-Z0-9._-]*$'

      - name: Validate profile.json schema
        uses: walbo/validate-json@v1.1.0
        with:
          files: ./*/profile.json
          schema: profile.schema.json
          schema-version: draft-07
          fail-on-missing-schema: true
      - name: Validate chains.json schema
        uses: walbo/validate-json@v1.1.0
        with:
          files: ./*/chains.json
          schema: chains.schema.json
          schema-version: draft-07
          fail-on-missing-schema: true